pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Database', '~> 5.15.0'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NavPrac' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NavPrac

#  target 'NavPrac-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

  target 'NavPracTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'NavPrac-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NavPrac-tvOS

#  target 'NavPrac-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

#end
